# The URL the site will be built for
base_url = "https://mop.koeln"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"
title = "mop.koeln"
description = "Andreas Streichardt Softwareentwicklung"

taxonomies = [
  {name = "tags"}, # each tag will have its own RSS feed
]

generate_feed = true
feed_filename = "rss.xml"

[markdown]
render_emoji = true

[extra]
use_cdn = false
socials = [
    { name= "twitter", url= "https://twitter.com/m0ppers", icon= "twitter" },
    { name= "github", url= "https://github.com/m0ppers", icon = "github" },
    { name= "linkedin", url= "https://www.linkedin.com/in/andreas-streichardt-71a181aa/", icon = "linkedin" },
]
menu = [
    { name= "Blog", url= "/blog/" },
    { name= "Contact", url= "/contact"},
    { name= "Impressum (de)", url= "/impressum" },
    { name= "Datenschutzerklärung (de)", url= "/datenschutzerklaerung" },
]