# The URL the site will be built for
base_url = "https://mop.koeln"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"
title = "mop.koeln"
description = "Andreas Streichardt Softwareentwicklung"

taxonomies = [
  {name = "tags"}, # each tag will have its own RSS feed
]

generate_feed = true
feed_filename = "rss.xml"

[markdown]
render_emoji = true

[extra]
# Put all your custom variables here
hyde_links = [
    {url = "/blog", name = "Blog"},
    {url = "/contact", name = "Contact"},
    {url = "/impressum", name = "Impressum (de)"},
    {url = "/datenschutzerklaerung", name = "Datenschutzerklärung (de)"},
    {url = "https://github.com/m0ppers", name = "Github"},
    {url = "https://twitter.com/m0ppers", name = "Twitter"},
    {url = "https://www.linkedin.com/in/andreas-streichardt-71a181aa/", name = "LinkedIn"},
]